bundler_args: --without yard guard metrics benchmarks
before_install:
  - gem install bundler --pre
branches:
  only:
    - /^release-.*$/
script: "bundle exec rake spec"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
env:
  - "GIT_BRANCH=release-1.2 ADAPTER=yaml"
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - dan.kubb@gmail.com
